import * as React from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { PowerIcon, Trash2Icon } from "lucide-react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Textarea } from "@/components/ui/textarea"
import { ConfirmAction } from "@/components/admin/AdminPrimitives"
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field"
import { adminApi, errorMessage } from "@/lib/admin/api"
import type { Team } from "@/lib/admin/types"
import { normalizeLoginCodeInput } from "@/lib/login-code"

type EnabledFilter = "all" | "enabled" | "disabled"

type TeamForm = {
  name: string
  login_code: string
  note: string
}

const emptyTeamForm: TeamForm = {
  name: "",
  login_code: "",
  note: "",
}

function enabledParam(filter: EnabledFilter) {
  if (filter === "enabled") return true
  if (filter === "disabled") return false
  return null
}

function formatDate(value: string) {
  return new Intl.DateTimeFormat(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value))
}

function parseBulkTeams(value: string) {
  return value
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      const [name = "", login_code = "", ...noteParts] = line
        .split(/[\t,]/)
        .map((part) => part.trim())

      return {
        name,
        login_code: login_code ? normalizeLoginCodeInput(login_code) : undefined,
        note: noteParts.join(", ") || undefined,
      }
    })
    .filter((team) => team.name)
}

function TeamDialog({
  mode,
  open,
  initialValue,
  isSaving,
  error,
  onOpenChange,
  onSubmit,
}: {
  mode: "create" | "edit"
  open: boolean
  initialValue: TeamForm
  isSaving: boolean
  error: string | null
  onOpenChange: (open: boolean) => void
  onSubmit: (value: TeamForm) => void
}) {
  const [form, setForm] = React.useState<TeamForm>(initialValue)

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>{mode === "create" ? "Create team" : "Edit team"}</DialogTitle>
          <DialogDescription>
            Team names are visible on the leaderboard. Login codes can be supplied manually or generated by the server.
          </DialogDescription>
        </DialogHeader>
        <form
          onSubmit={(event) => {
            event.preventDefault()
            onSubmit(form)
          }}
        >
          <FieldGroup>
          <Field>
            <FieldLabel htmlFor={`${mode}-team-name`}>Team name</FieldLabel>
            <Input
              id={`${mode}-team-name`}
              required
              value={form.name}
              onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))}
              placeholder="Green Turtles"
            />
          </Field>
          <Field>
            <FieldLabel htmlFor={`${mode}-team-login-code`}>Login code</FieldLabel>
            <Input
              id={`${mode}-team-login-code`}
              value={form.login_code}
              onChange={(event) =>
                setForm((current) => ({ ...current, login_code: normalizeLoginCodeInput(event.target.value) }))
              }
              placeholder={mode === "create" ? "Leave blank to auto-generate" : "Current login code"}
              autoCapitalize="characters"
            />
          </Field>
          <Field>
            <FieldLabel htmlFor={`${mode}-team-note`}>Note</FieldLabel>
            <Textarea
              id={`${mode}-team-note`}
              value={form.note}
              onChange={(event) => setForm((current) => ({ ...current, note: event.target.value }))}
              placeholder="Internal admin note"
            />
          </Field>
          {error ? <p className="text-sm text-destructive">{error}</p> : null}
          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
              Cancel
            </Button>
            <Button type="submit" disabled={isSaving || !form.name.trim()}>
              {isSaving ? "Saving..." : mode === "create" ? "Create team" : "Save changes"}
            </Button>
          </DialogFooter>
          </FieldGroup>
        </form>
      </DialogContent>
    </Dialog>
  )
}

export default function AdminTeamsPage() {
  const queryClient = useQueryClient()
  const [search, setSearch] = React.useState("")
  const [enabled, setEnabled] = React.useState<EnabledFilter>("all")
  const [createOpen, setCreateOpen] = React.useState(false)
  const [bulkOpen, setBulkOpen] = React.useState(false)
  const [bulkText, setBulkText] = React.useState("")
  const [editingTeam, setEditingTeam] = React.useState<Team | null>(null)
  const [actionError, setActionError] = React.useState<string | null>(null)

  const teamsQuery = useQuery({
    queryKey: ["admin", "teams", { enabled, search }],
    queryFn: () => adminApi.teams({ enabled: enabledParam(enabled), search }),
  })

  const invalidateTeams = () => queryClient.invalidateQueries({ queryKey: ["admin", "teams"] })

  const createTeam = useMutation({
    mutationFn: (form: TeamForm) =>
      adminApi.createTeam({
        name: form.name.trim(),
        login_code: normalizeLoginCodeInput(form.login_code).trim() || undefined,
        note: form.note.trim() || undefined,
      }),
    onSuccess: () => {
      setCreateOpen(false)
      setActionError(null)
      invalidateTeams()
    },
    onError: (error) => setActionError(errorMessage(error)),
  })

  const bulkCreate = useMutation({
    mutationFn: (value: string) => adminApi.bulkCreateTeams(parseBulkTeams(value)),
    onSuccess: () => {
      setBulkOpen(false)
      setBulkText("")
      setActionError(null)
      invalidateTeams()
    },
    onError: (error) => setActionError(errorMessage(error)),
  })

  const updateTeam = useMutation({
    mutationFn: ({ id, form }: { id: string; form: TeamForm }) =>
      adminApi.updateTeam(id, {
        name: form.name.trim(),
        login_code: normalizeLoginCodeInput(form.login_code).trim(),
        note: form.note.trim() || null,
      }),
    onSuccess: () => {
      setEditingTeam(null)
      setActionError(null)
      invalidateTeams()
    },
    onError: (error) => setActionError(errorMessage(error)),
  })

  const rotateCode = useMutation({
    mutationFn: (team: Team) => adminApi.rotateTeamCode(team.id),
    onSuccess: () => invalidateTeams(),
    onError: (error) => setActionError(errorMessage(error)),
  })

  const setTeamEnabled = useMutation({
    mutationFn: (team: Team) => (team.enabled ? adminApi.disableTeam(team.id) : adminApi.enableTeam(team.id)),
    onSuccess: () => {
      setActionError(null)
      invalidateTeams()
    },
    onError: (error) => setActionError(errorMessage(error)),
  })

  const deleteTeam = useMutation({
    mutationFn: (team: Team) => adminApi.deleteTeam(team.id),
    onSuccess: () => {
      setActionError(null)
      invalidateTeams()
    },
    onError: (error) => setActionError(errorMessage(error)),
  })

  const teams = teamsQuery.data ?? []
  const activeCount = teams.filter((team) => team.enabled).length
  const parsedBulkCount = parseBulkTeams(bulkText).length

  return (
    <div className="grid gap-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <h1 className="font-heading text-2xl font-semibold tracking-tight">Teams</h1>
          <p className="text-sm text-muted-foreground">
            Search, create, bulk-create, edit, rotate login codes, disable logins, and delete teams.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button variant="outline" onClick={() => setBulkOpen(true)}>
            Bulk create
          </Button>
          <Button onClick={() => setCreateOpen(true)}>Create team</Button>
        </div>
      </div>

      <div className="grid gap-3 sm:grid-cols-3">
        <Card>
          <CardHeader>
            <CardDescription>Total shown</CardDescription>
            <CardTitle className="text-2xl">{teams.length}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader>
            <CardDescription>Enabled shown</CardDescription>
            <CardTitle className="text-2xl">{activeCount}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader>
            <CardDescription>Combined score</CardDescription>
            <CardTitle className="text-2xl">
              {teams.reduce((sum, team) => sum + team.total_score, 0)}
            </CardTitle>
          </CardHeader>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Team directory</CardTitle>
          <CardDescription>Filters run against the admin teams endpoint.</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-4">
          <div className="flex flex-col gap-2 sm:flex-row">
            <Input
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              placeholder="Search team name or code"
              className="sm:max-w-sm"
            />
            <Select items={[{ value: "all", label: "All teams" }, { value: "enabled", label: "Enabled" }, { value: "disabled", label: "Disabled" }]} value={enabled} onValueChange={(value) => setEnabled(value as EnabledFilter)}>
              <SelectTrigger className="w-full sm:w-40">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All teams</SelectItem>
                <SelectItem value="enabled">Enabled</SelectItem>
                <SelectItem value="disabled">Disabled</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {actionError ? <p className="text-sm text-destructive">{actionError}</p> : null}
          {teamsQuery.isError ? <p className="text-sm text-destructive">{errorMessage(teamsQuery.error)}</p> : null}

          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Name</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Login code</TableHead>
                <TableHead className="text-right">Score</TableHead>
                <TableHead>Updated</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {teamsQuery.isLoading ? (
                <TableRow>
                  <TableCell colSpan={6} className="py-8 text-center text-muted-foreground">
                    Loading teams...
                  </TableCell>
                </TableRow>
              ) : teams.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={6} className="py-8 text-center text-muted-foreground">
                    No teams match the current filters.
                  </TableCell>
                </TableRow>
              ) : (
                teams.map((team) => (
                  <TableRow key={team.id}>
                    <TableCell>
                      <div className="font-medium">{team.name}</div>
                      {team.note ? <div className="max-w-72 truncate text-xs text-muted-foreground">{team.note}</div> : null}
                    </TableCell>
                    <TableCell>
                      <Badge variant={team.enabled ? "secondary" : "outline"}>
                        {team.enabled ? "Enabled" : "Disabled"}
                      </Badge>
                    </TableCell>
                    <TableCell className="font-mono text-xs">{team.login_code}</TableCell>
                    <TableCell className="text-right font-medium">{team.total_score}</TableCell>
                    <TableCell>{formatDate(team.updated_at)}</TableCell>
                    <TableCell>
                      <div className="flex flex-wrap justify-end gap-2">
                        <Button variant="outline" size="sm" onClick={() => setEditingTeam(team)}>
                          Edit
                        </Button>
                        <ConfirmAction
                          title="Rotate login code"
                          description={`Rotate login code for ${team.name}? The old code will stop working.`}
                          confirmLabel="Rotate"
                          disabled={rotateCode.isPending}
                          onConfirm={() => rotateCode.mutate(team)}
                        >
                          <Button variant="outline" size="sm">Rotate</Button>
                        </ConfirmAction>
                        <ConfirmAction
                          title={team.enabled ? "Disable team" : "Enable team"}
                          description={
                            team.enabled
                              ? `${team.name} will not be able to log in, submit, or vote until enabled again.`
                              : `${team.name} will be able to log in, submit, and vote again.`
                          }
                          confirmLabel={team.enabled ? "Disable" : "Enable"}
                          destructive={team.enabled}
                          disabled={setTeamEnabled.isPending}
                          onConfirm={() => setTeamEnabled.mutate(team)}
                        >
                          <Button variant={team.enabled ? "outline" : "default"} size="sm">
                            <PowerIcon data-icon="inline-start" />
                            {team.enabled ? "Disable" : "Enable"}
                          </Button>
                        </ConfirmAction>
                        <ConfirmAction
                          title="Delete team permanently"
                          description={`${team.name} and its submissions, scores, and active game references will be permanently deleted.`}
                          confirmLabel="Delete permanently"
                          destructive
                          disabled={deleteTeam.isPending}
                          onConfirm={() => deleteTeam.mutate(team)}
                        >
                          <Button variant="destructive" size="sm">
                            <Trash2Icon data-icon="inline-start" />
                            Delete
                          </Button>
                        </ConfirmAction>
                      </div>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {createOpen ? (
        <TeamDialog
          mode="create"
          open={createOpen}
          initialValue={emptyTeamForm}
          isSaving={createTeam.isPending}
          error={createTeam.isError ? errorMessage(createTeam.error) : null}
          onOpenChange={(open) => {
            setCreateOpen(open)
            setActionError(null)
          }}
          onSubmit={(form) => createTeam.mutate(form)}
        />
      ) : null}

      {editingTeam ? (
        <TeamDialog
          key={editingTeam.id}
          mode="edit"
          open={editingTeam !== null}
          initialValue={{
            name: editingTeam.name,
            login_code: editingTeam.login_code,
            note: editingTeam.note ?? "",
          }}
          isSaving={updateTeam.isPending}
          error={updateTeam.isError ? errorMessage(updateTeam.error) : null}
          onOpenChange={(open) => {
            if (!open) setEditingTeam(null)
            setActionError(null)
          }}
          onSubmit={(form) => {
            updateTeam.mutate({ id: editingTeam.id, form })
          }}
        />
      ) : null}

      <Dialog open={bulkOpen} onOpenChange={setBulkOpen}>
        <DialogContent className="sm:max-w-2xl">
          <DialogHeader>
            <DialogTitle>Bulk create teams</DialogTitle>
            <DialogDescription>
              Add one team per line. Use comma or tab separated values: name, optional login code, optional note.
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-3">
            <Textarea
              value={bulkText}
              onChange={(event) => setBulkText(event.target.value)}
              className="min-h-56 font-mono"
              placeholder={"Green Turtles,GT-102,Coach: Lin\nBlue Turtles\nRed Turtles,RED-7"}
            />
            <p className="text-sm text-muted-foreground">{parsedBulkCount} valid teams parsed.</p>
            {bulkCreate.isError ? <p className="text-sm text-destructive">{errorMessage(bulkCreate.error)}</p> : null}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setBulkOpen(false)}>
              Cancel
            </Button>
            <Button
              disabled={bulkCreate.isPending || parsedBulkCount === 0}
              onClick={() => bulkCreate.mutate(bulkText)}
            >
              {bulkCreate.isPending ? "Creating..." : "Create teams"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
